polipo:
  image: lihaixin/polipo
  command:
    proxyAddress=0.0.0.0
    proxyPort=8123
    authCredentials=username:password
    socksParentProxy=1.2.3.4:8123
  ports:
    - "8123:8123"
  restart: always
